### ISSUE TITLE
Linking problems with glog and leveldb

### ISSUE THREAD

**Issue by lukeyeager** [AnacondaRecipes/caffe-feedstock#1]
(Originally posted here: https://github.com/conda-forge/caffe-feedstock/issues/42)

When I install like this:
```
conda install -y -c anaconda caffe
```
I get errors like this:
```
/opt/conda/lib/python3.6/site-packages/caffe/../../../libcaffe.so.1.0.0:
    undefined symbol: _ZNK7leveldb6Status8ToStringB5cxx11Ev
```
I used this to fix it (upgraded these packages to the latest version):
```
conda install -y glog leveldb
```

**Comment by jjhelmus** [comment]
@lukeyeager You should avoid the use of the `anaconda` channel.  It mixes packages from the various sub-channels which make up the `defaults` channel without the appropriate priorities.  A better method is install packages using either `conda install caffe` or `conda install -c defaults caffe`. 

You also mention `conda-forge`.  Mixing packages between `defaults` and `conda-forge` can be problematic as many are currently incompatible.  This is especially true for the dependencies of `caffe`.  The best method is to choose either `defaults` or `conda-forge` as the highest priority channel when creating an environment and maintain that priority when installing new packages into the environment.  Changing the priority between transaction can lead to issues like you describe.  

My best guess is that your environment contained a mixture of packages from different channels that were incompatible.  We are working to make `conda-forge` and `defaults` more compatible but this will take some time.

**Comment by lukeyeager** [comment]
@jjhelmus OK, trying that now. FYI, when you google "conda caffe", you get these two options for how to install caffe. Sound like neither is the recommended method.

> conda install -c anaconda caffe
https://anaconda.org/anaconda/caffe

> conda install -c conda-forge caffe
https://anaconda.org/conda-forge/caffe

**Comment by jjhelmus** [comment]
@lukeyeager That is unfortunate.  Both of those instructions are automatically generated so there is not much we (Anaconda) can do to change them.  The [Anaconda Documentation](http://docs.anaconda.com/anaconda/user-guide/tasks/gpu-packages/?highlight=caffe) recommends the command `conda install caffe-gpu` for installing the GPU version of Caffe but does not include instructions for non-GPU installs.  I'll look into adding that topic to the docs.
